// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R4D
// for eadrkir (eadrkir@eadrkir-VirtualBox) on Mon Apr 18 14:18:01 2016

// Copyright (c) 2000-2015 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "loopbackPort.hh"

namespace Sem__0902__Communication__ports__001 {

loopbackPort::loopbackPort(const char *par_port_name)
	: loopbackPort_BASE(par_port_name)
{

}

loopbackPort::~loopbackPort()
{

}

void loopbackPort::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void loopbackPort::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void loopbackPort::Handle_Fd_Event_Error(int /*fd*/)
{

}

void loopbackPort::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void loopbackPort::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void loopbackPort::Handle_Timeout(double time_since_last_call) {}*/

void loopbackPort::user_map(const char * /*system_port*/)
{

}

void loopbackPort::user_unmap(const char * /*system_port*/)
{

}

void loopbackPort::user_start()
{

}

void loopbackPort::user_stop()
{

}

void loopbackPort::outgoing_send(const INTEGER& send_par)
{
	incoming_message(send_par);
}

} /* end of namespace */

