// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R4D
// for eadrkir (eadrkir@eadrkir-VirtualBox) on Mon Apr 18 14:18:01 2016

// Copyright (c) 2000-2016 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "loopbackPort1.hh"

namespace Sem__0902__Communication__ports__002 {

loopbackPort1::loopbackPort1(const char *par_port_name)
	: loopbackPort1_BASE(par_port_name)
{

}

loopbackPort1::~loopbackPort1()
{

}

void loopbackPort1::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void loopbackPort1::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void loopbackPort1::Handle_Fd_Event_Error(int /*fd*/)
{

}

void loopbackPort1::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void loopbackPort1::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void loopbackPort1::Handle_Timeout(double time_since_last_call) {}*/

void loopbackPort1::user_map(const char * /*system_port*/)
{

}

void loopbackPort1::user_unmap(const char * /*system_port*/)
{

}

void loopbackPort1::user_start()
{

}

void loopbackPort1::user_stop()
{

}

void loopbackPort1::outgoing_send(const INTEGER& send_par)
{
	incoming_message(send_par);
}

} /* end of namespace */

