// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R4A
// for eadrkir (eadrkir@eadrkir-VirtualBox) on Mon Jan 18 12:27:53 2016

// Copyright (c) 2000-2015 Ericsson Telecom AB

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "IntegerOutputPortType.hh"

namespace Sem__0902__Communication__ports__001 {

IntegerOutputPortType::IntegerOutputPortType(const char *par_port_name)
	: IntegerOutputPortType_BASE(par_port_name)
{

}

IntegerOutputPortType::~IntegerOutputPortType()
{

}

void IntegerOutputPortType::set_parameter(const char * /*parameter_name*/,
	const char * /*parameter_value*/)
{

}

/*void IntegerOutputPortType::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void IntegerOutputPortType::Handle_Fd_Event_Error(int /*fd*/)
{

}

void IntegerOutputPortType::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void IntegerOutputPortType::Handle_Fd_Event_Readable(int /*fd*/)
{

}

/*void IntegerOutputPortType::Handle_Timeout(double time_since_last_call) {}*/

void IntegerOutputPortType::user_map(const char * /*system_port*/)
{

}

void IntegerOutputPortType::user_unmap(const char * /*system_port*/)
{

}

void IntegerOutputPortType::user_start()
{

}

void IntegerOutputPortType::user_stop()
{

}

void IntegerOutputPortType::outgoing_send(const INTEGER& /*send_par*/)
{

}

} /* end of namespace */

